# TYPE    DATABASE  USER  ADDRESS       METHOD    OPTIONS
local     all       all                 trust
hostssl   all       all   0.0.0.0/0     cert      clientcert=verify-full
host      all       all   0.0.0.0/0     reject