services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped # Ensures the container restarts automatically if it crashes or the host reboots
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/pass_1234

# Defining the named volumes managed by Docker
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
