spring:
  application:
    name: open-telemetry

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
    resource-attributes:
      service.name: open-telemetry
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: open-telemetry
  endpoints:
    web:
      exposure:
        include: "*"

server:
  shutdown: immediate

logging:
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"