spring:
  application:
    name: spring-batch

  datasource:
    url: jdbc:postgresql://localhost:5435/spring_test
    username: postgres
    password: pass_1234
    driver-class-name: org.postgresql.Driver

  # Jpa properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          ordering: true

  cloud:
    aws:
      s3:
        endpoint: http://localhost:4866
        bucket-name: employee-csv
        path-style-access-enabled: true
        region: us-east-1
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test


  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB # Avoid buffering file uploads entirely in memory [1]

  batch:
    job:
      enabled: false